travis:
  secure:
    BINSTAR_TOKEN: noYcJ6bS60m0IoIjCNJjiLQvpIwUteBM5gJ9Yd8IZGB90clQPYuxyZDaUWfAoxpIv4DW8HlvFOGhXupWfpClfiZDAL4LW0dYuoSTnimjaMWn8D56fNIKMy2TGhMI3X4WHIPxelLYyWfm2TLBIzXjszJEyG80cjvrNEeyafJi75CUkl0CEvenEjfXkDMjs+avAF2N0IcxUOmY7/Zvn9qEMNkEf1FJFcfkN89Vwhxrhi2dWc22KA7U7P36RgK0YRsHatV1KfSR+IezgwsGTU+Ja8AEcvN5QXlngHuk0Uzp9qQabw5ONMbVjGU5vcmoJyQJRMOY+ODDeSUAgJVbz06AFZzhafm86OPe6ijqWx0j0JRLNhG1QPj3suI4Yw+/BBlLZjZK9y5o5uaCBReFHlE2nJdoQvqgueM256gcmdGqKBxE/r0CxFiGFBFyJD0N/Z1SDsQr4pVmCb0iET54T8LNQeSi+NuaqEScO7MQcmijs3Erx2qwP8tfJDD3nN7/eCvHPZd8habLTHxevkVDrve+jrKDHRg9WHn0FURdXjYBpictwK6QYFz3YnxMJZeh+36jOCISuxRsNq4rtAhu+pIiagjDHr7QXkyO4Zen1w3hRC4k/kTN2246ctR0szjxLnND+W38JzTrIUx73Z1inliadHrAKv3Q8EdTnZSg6nF9uSM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
